import { create } from 'zustand';
export const useRecommendationStore = create((set) => ({
    photoBase64: null,
    analysis: null,
    recommendations: null,
    activeBase: null,
    activeBatom: null,
    activeBlush: null,
    isLoading: false,
    error: null,
    setPhoto: (base64) => set({ photoBase64: base64 }),
    setResult: (analysis, recs) => set({
        analysis,
        recommendations: recs,
        activeBase: recs.base,
        activeBatom: recs.batom,
        activeBlush: recs.blush,
        isLoading: false,
        error: null,
    }),
    setActiveBase: (p) => set({ activeBase: p }),
    setActiveBatom: (p) => set({ activeBatom: p }),
    setActiveBlush: (p) => set({ activeBlush: p }),
    setLoading: (v) => set({ isLoading: v }),
    setError: (e) => set({ error: e, isLoading: false }),
    reset: () => set({
        photoBase64: null,
        analysis: null,
        recommendations: null,
        activeBase: null,
        activeBatom: null,
        activeBlush: null,
        isLoading: false,
        error: null,
    }),
}));
